### ISSUE TITLE
Capture Finish Button Return

### ISSUE THREAD

**Issue by abstertee** [PezzaD84/Assemble#2]
Trying to figure out how we can capture the output of the Finish button to perform other actions.  For example, trying to restart the system instead of just closing out the dialog window.
[Finish Button Code](https://github.com/PezzaD84/Assemble/blob/d177e3c9246be4857c7afda364a718e3b2dc21d7/Assemble-Template#L579)

**Comment by PezzaD84** [comment]
Hi @abstertee 
Sorry for the delay in replying. So if the device needs a reboot to enable FleVault the button will change to a reboot button and it runs the following command `--button1shellaction "launchctl bootout user/$(id -u $CURRENT_USER)"`

If you want to modify this to give you a reboot all the time then feel free to add this code to the end message.
